AllCops:
  TargetRubyVersion: 3.0
  DefaultFormatter: simple
  NewCops: disable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - '*.gemspec'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 25
